var searchData=
[
  ['déplacement_20de_20la_20pièce_0',['4.4 - Déplacement de la pièce',['../tp3.html#TP3-deplacepiece',1,'']]],
  ['déplacer_20la_20pièce_1',['5.2 - Touches pour déplacer la pièce',['../tp3.html#TP3-touches',1,'']]],
  ['détection_20de_20la_20fin_20de_20la_20partie_2',['3.7 - Détection de la fin de la partie',['../tp2.html#TP2-fin',1,'']]],
  ['développements_20optionnels_3',['Développements optionnels',['../tp1.html#OptP4',1,'']]],
  ['d_20action_4',['5 - Un peu d&apos;action',['../tp3.html#TP3-timer',1,'']]],
  ['d_20exécution_20ddd_5',['9 - Pointeurs, pile d&apos;exécution, ddd',['../tp1.html#huit',1,'']]],
  ['d_20un_20makefile_6',['2.2 - Création d&apos;un makefile',['../tp3.html#TP3-makefile',1,'']]],
  ['d_20un_20programme_20c_7',['Valeur de retour et paramètres d&apos;un programme C.',['../tp1.html#params',1,'']]],
  ['d_20un_20tri_20à_20bulle_20avec_20ddd_8',['4 - Correction d&apos;un tri à bulle avec ddd',['../tp1.html#quatre',1,'']]],
  ['d_20une_20autre_20fonction_9',['Tracé d&apos;une autre fonction',['../tp1.html#trace_fct',1,'']]],
  ['d_20une_20liste_20chaînée_10',['4 - Implémentation à l&apos;aide d&apos;une liste chaînée',['../tp2.html#TP2-liste',1,'']]],
  ['dans_20la_20grille_11',['3.5 - Écriture dans la grille',['../tp2.html#TP2-ecriture',1,'']]],
  ['dans_20la_20zone_20de_20dessin_12',['4 - Affichage du Tetris dans la zone de dessin.',['../tp3.html#TP3-dessin',1,'']]],
  ['ddd_13',['ddd',['../tp1.html#Trois',1,'3 - Debugger ddd'],['../tp1.html#quatre',1,'4 - Correction d&apos;un tri à bulle avec ddd'],['../tp1.html#huit',1,'9 - Pointeurs, pile d&apos;exécution, ddd'],['../tp1.html',1,'TP1 - Enoncé - Quelques algorithmes simples, tracés, et récursivité, debugger ddd']]],
  ['de_20dessin_14',['4 - Affichage du Tetris dans la zone de dessin.',['../tp3.html#TP3-dessin',1,'']]],
  ['de_20garanties_20possible_15',['Compiler avec le maximum de garanties possible',['../tp1.html#mygcc',1,'']]],
  ['de_20l_20ihm_16',['3.4 - Mise en page de l&apos;IHM',['../tp3.html#TP3-mise_en_page',1,'']]],
  ['de_20la_20fin_20de_20la_20partie_17',['3.7 - Détection de la fin de la partie',['../tp2.html#TP2-fin',1,'']]],
  ['de_20la_20grille_18',['de la grille',['../tp2.html#TP2-affichage',1,'3.3 - Initialisation et affichage de la grille'],['../tp3.html#TP3-grille',1,'4.2 - Dessin de la grille']]],
  ['de_20la_20pièce_19',['de la pièce',['../tp3.html#TP3-deplacepiece',1,'4.4 - Déplacement de la pièce'],['../tp3.html#TP3-placepiece',1,'4.5 - Placement de la pièce']]],
  ['de_20la_20pièce_20en_20attente_20',['4.3 - Affichage de la pièce en attente',['../tp3.html#TP3-affichepiece',1,'']]],
  ['de_20la_20tortue_21',['Codage de la tortue',['../tp1.html#logo_code',1,'']]],
  ['de_20lignes_22',['3.8 - Effacement de lignes',['../tp2.html#TP2-effacement',1,'']]],
  ['de_20retour_20et_20paramètres_20d_20un_20programme_20c_23',['Valeur de retour et paramètres d&apos;un programme C.',['../tp1.html#params',1,'']]],
  ['de_20tracé_20pour_20illustrer_20des_20algorithmes_20simples_24',['6 - Un peu de tracé pour illustrer des algorithmes simples',['../tp1.html#trace',1,'']]],
  ['debugger_20ddd_25',['debugger ddd',['../tp1.html#Trois',1,'3 - Debugger ddd'],['../tp1.html',1,'TP1 - Enoncé - Quelques algorithmes simples, tracés, et récursivité, debugger ddd']]],
  ['des_20algorithmes_20simples_26',['6 - Un peu de tracé pour illustrer des algorithmes simples',['../tp1.html#trace',1,'']]],
  ['des_20entrées_27',['3.6 - Lecture des entrées',['../tp2.html#TP2-lecture',1,'']]],
  ['des_20pièces_28',['3.4 - Génération et affichage des pièces',['../tp2.html#TP2-pieces',1,'']]],
  ['dessin_29',['4 - Affichage du Tetris dans la zone de dessin.',['../tp3.html#TP3-dessin',1,'']]],
  ['dessin_20de_20la_20grille_30',['4.2 - Dessin de la grille',['../tp3.html#TP3-grille',1,'']]],
  ['données_31',['3.6 - Accès à toutes les données',['../tp3.html#TP3-donnees',1,'']]],
  ['double_20boucles_32',['10 - Double boucles',['../tp1.html#dix',1,'']]],
  ['draw_20events_33',['4.1 - Realize et draw events',['../tp3.html#TP3-expose',1,'']]],
  ['du_20jeu_20tetris_34',['2 - Une version simplifiée du jeu Tetris',['../tp2.html#TP2-jeu',1,'']]],
  ['du_20programme_20en_20c_35',['3 - Réalisation du programme en C',['../tp2.html#TP2-prog',1,'']]],
  ['du_20tetris_20dans_20la_20zone_20de_20dessin_36',['4 - Affichage du Tetris dans la zone de dessin.',['../tp3.html#TP3-dessin',1,'']]],
  ['du_20tp_37',['6 - Remise du tp',['../tp3.html#TP3-divers',1,'']]]
];
