SRC=~/MyCore/Cours/INFO804/Tests/WebGL

all: algosurfer

algosurfer:
	cp ${SRC}/algosurfer.html .
	cp ${SRC}/shaders-implicit-surface-viewer.html .
	cp ${SRC}/chunk-functions.html .
	cp ${SRC}/chunk-info.html .
	cp ${SRC}/chunk-shaders.html .

