INFO607: TP-Proximity/main.c File Reference
main.c File Reference
#include <stdlib.h>
#include <math.h>
#include <assert.h>
#include <gtk/gtk.h>
#include "points.h"
#include "particules.h"
#include "forces.h"
Classes
struct SContexte
Macros
#define DT 0.01
#define DT_AFF 0.02
Typedefs
typedef struct SContexte Contexte
Functions
GtkWidget * creerIHM (Contexte *pCtxt)
Charge l'image donnée et crée l'interface.
gboolean on_draw (GtkWidget *widget, GdkEventExpose *event, gpointer data)
Point point2DrawingAreaPoint (Contexte *pCtxt, Point p)
double length2DrawingAreaLength (Contexte *pCtxt, double l)
Point drawingAreaPoint2Point (Contexte *pCtxt, Point p)
void drawParticule (Contexte *pCtxt, cairo_t *cr, Particule p)
void drawPoint (cairo_t *cr, double x, double y, double r)
gint tic (gpointer data)
gint ticAffichage (gpointer data)
gint ticDistance (gpointer data)
void calculDynamique (Contexte *pCtxt)
void deplaceTout (Contexte *pCtxt)
void deplaceParticule (Contexte *pCtxt, Particule *p)
void fontaine (Contexte *pCtxt, double p, double x, double y, double vx, double vy, double m)
int main (int argc, char *argv[])
void drawLine (cairo_t *cr, Point p, Point q)
Macro Definition Documentation
DT
#define DT 0.01
Definition at line 27 of file main.c.
DT_AFF
#define DT_AFF 0.02
Definition at line 29 of file main.c.
Typedef Documentation
Contexte
typedef struct SContexte Contexte
Le contexte contient les informations utiles de l'interface pour les algorithmes de géométrie algorithmique.
Function Documentation
calculDynamique()
void calculDynamique (Contexte * pCtxt)
Calcul la dynamique de tous les points en appliquant les forces et met à jour la vitesse.
Definition at line 346 of file main.c.
{
  TabParticules* P = &pCtxt->TabP;
  int n = TabParticules_nb( P );
  Force* F = pCtxt->forces;
  // On met à zéro les forces de chaque point.
  for ( int i = 0; i < n; ++i )
    {
      Particule* p = TabParticules_ref( P, i );
      p->f[ 0 ] = 0.0;
      p->f[ 1 ] = 0.0;
    }
  // On applique les forces à tous les points
  for ( int i = 0; i < n; ++i )
    {
      Particule* p = TabParticules_ref( P, i );
      for ( int j = 0; j < NB_FORCES; ++j )
        appliqueForce( p, &F[ j ] );
    }
  // On applique la loi de Newton: masse*acceleration = somme des forces
  // ie m dv/dt = sum f
  // ie v[t+dt] = v[t] + (dt/m) * sum f
  for ( int i = 0; i < n; ++i )
    {
      Particule* p = TabParticules_ref( P, i );
      p->v[ 0 ] += (DT / p->m) * p->f[ 0 ];
      p->v[ 1 ] += (DT / p->m) * p->f[ 1 ];
    }
}
References appliqueForce(), DT, SParticule::f, SContexte::forces, SParticule::m, NB_FORCES, SContexte::TabP, TabParticules_nb(), TabParticules_ref(), and SParticule::v.
Referenced by tic().
creerIHM()
GtkWidget * creerIHM (Contexte * pCtxt)
Charge l'image donnée et crée l'interface.
Crée l'interface graphique en fonction du contexte pCtxt.
Definition at line 238 of file main.c.
{
  GtkWidget* window;
  GtkWidget* vbox1;
  GtkWidget* vbox2;
  GtkWidget* hbox1;
  GtkWidget* button_quit;
  /* Crée une fenêtre. */
  window = gtk_window_new( GTK_WINDOW_TOPLEVEL );
  // Crée un conteneur horizontal box.
  hbox1 = gtk_box_new( GTK_ORIENTATION_HORIZONTAL, 10 );
  // Crée deux conteneurs vertical box.
  vbox1 = gtk_box_new( GTK_ORIENTATION_VERTICAL, 10 );
  vbox2 = gtk_box_new( GTK_ORIENTATION_VERTICAL, 10 );
  // Crée une zone de dessin
  pCtxt->drawing_area = gtk_drawing_area_new();
  pCtxt->width  = 500;
  pCtxt->height = 500;
  gtk_widget_set_size_request ( pCtxt->drawing_area, pCtxt->width, pCtxt->height );
  // Crée le pixbuf source et le pixbuf destination
  gtk_container_add( GTK_CONTAINER( hbox1 ), pCtxt->drawing_area );
  // ... votre zone de dessin s'appelle ici "drawing_area"
  g_signal_connect( G_OBJECT ( pCtxt->drawing_area ), "draw",
                    G_CALLBACK( on_draw ), pCtxt );
  // Rajoute le 2eme vbox dans le conteneur hbox (pour mettre les boutons sélecteur de points
  gtk_container_add( GTK_CONTAINER( hbox1 ), vbox2 );
  // Crée les labels pour afficher le nombre de points et le nombre
  // d'appel à la fonction distance.
  pCtxt->label_nb = gtk_label_new( "0 points" );
  gtk_container_add( GTK_CONTAINER( vbox2 ), pCtxt->label_nb );
  pCtxt->label_distance = gtk_label_new( "" );
  gtk_container_add( GTK_CONTAINER( vbox2 ), pCtxt->label_distance );
  // Crée le bouton quitter.
  button_quit = gtk_button_new_with_label( "Quitter" );
  // Connecte la réaction gtk_main_quit à l'événement "clic" sur ce bouton.
  g_signal_connect( button_quit, "clicked",
                    G_CALLBACK( gtk_main_quit ),
                    NULL);
  // Rajoute tout dans le conteneur vbox.
  gtk_container_add( GTK_CONTAINER( vbox1 ), hbox1 );
  gtk_container_add( GTK_CONTAINER( vbox1 ), button_quit );
  // Rajoute la vbox  dans le conteneur window.
  gtk_container_add( GTK_CONTAINER( window ), vbox1 );
  // Rend tout visible
  gtk_widget_show_all( window );
  g_signal_connect (window, "destroy", G_CALLBACK (gtk_main_quit), NULL);
  // Crée les forces
  Force g = gravite( 0.0, -0.2 );
  pCtxt->forces[ 0 ] = g;
  // enclenche le timer pour se déclencher dans 5ms.
  g_timeout_add ( 1000*DT, tic, (gpointer) pCtxt );
  // enclenche le timer pour se déclencher dans 20ms.
  g_timeout_add ( 1000*DT_AFF, ticAffichage, (gpointer) pCtxt );
  // enclenche le timer pour se déclencher dans 1000ms.
  g_timeout_add ( 1000, ticDistance, (gpointer) pCtxt );
  return window;
}
References SContexte::drawing_area, DT, DT_AFF, SContexte::forces, gravite(), SContexte::height, SContexte::label_distance, SContexte::label_nb, on_draw(), tic(), ticAffichage(), ticDistance(), and SContexte::width.
Referenced by main().
deplaceParticule()
void deplaceParticule (Contexte * pCtxt, Particule * p)
Déplace une particule en fonction de sa vitesse. Devra s'occuper des collisions plus tard.
Definition at line 376 of file main.c.
{
  /* Déplace p en supposant qu'il n'y a pas de collision. */
  p->x[ 0 ] += DT * p->v[ 0 ];
  p->x[ 1 ] += DT * p->v[ 1 ];
}
References DT, SParticule::v, and SParticule::x.
Referenced by deplaceTout().
deplaceTout()
void deplaceTout (Contexte * pCtxt)
Déplace toutes les particules en fonction de leur vitesse.
Definition at line 383 of file main.c.
{
  TabParticules* P = &pCtxt->TabP;
  int n = TabParticules_nb( P );
  // Applique le vecteur vitesse sur toutes les particules.
  for ( int i = 0; i < n; ++i )
    {
      Particule* p = TabParticules_ref( P, i );
      deplaceParticule( pCtxt, p );
    }
  // Détruit les particules trop loin de la zone
  for ( int i = 0; i < TabParticules_nb( P ); )
    {
      Particule* p = TabParticules_ref( P, i );
      if ( ( p->x[ 0 ] < -1.5 ) || ( p->x[ 0 ] > 1.5 )
           || ( p->x[ 1 ] < -1.5 ) || ( p->x[ 1 ] > 1.5 ) )
        TabParticules_supprime( P, i );
      else ++i;
    }
}
References deplaceParticule(), SContexte::TabP, TabParticules_nb(), TabParticules_ref(), TabParticules_supprime(), and SParticule::x.
Referenced by tic().
drawingAreaPoint2Point()
Point drawingAreaPoint2Point (Contexte * pCtxt, Point p)
Fait la conversion coordonnées pixel de p vers coordonnées réelles.
Parameters
pCtxt le contexte de l'IHM
p les coordonnées pixel en entrée
Returns
ses coordonnées réelles.
Definition at line 205 of file main.c.
{
  Point q;
  q.x[ 0 ] = 2.0 * ((double)p.x[0] / (double)pCtxt->width) - 1.0;
  q.x[ 1 ] = -2.0 * ((double)p.x[1] / (double)pCtxt->height) + 1.0;
  return q;
}
References SContexte::height, SContexte::width, and SPoint::x.
drawLine()
void drawLine (cairo_t * cr, Point p, Point q)
Definition at line 230 of file main.c.
{
  cairo_move_to( cr, p.x[ 0 ], p.x[ 1 ] );
  cairo_line_to( cr, q.x[ 0 ], q.x[ 1 ]);
  cairo_stroke( cr );
}
References SPoint::x.
drawParticule()
void drawParticule (Contexte * pCtxt, cairo_t * cr, Particule p)
Affiche un point p dans une zone de dessin cairo cr comme un disque. La masse influe sur la taille d'affichage de la particule.
Parameters
cr le contexte CAIRO pour dessiner dans une zone de dessin.
p un point dans la zone de dessin.
Definition at line 213 of file main.c.
{
  Point pp;
  pp.x[ 0 ] = p.x[ 0 ];
  pp.x[ 1 ] = p.x[ 1 ];
  // On convertit les coordonnées réelles des particules (dans [-1:1]x[-1:1]) en coordonnées
  // de la zone de dessin (dans [0:499]x[0:499]).
  Point q = point2DrawingAreaPoint( pCtxt, pp );
  drawPoint( cr, q.x[ 0 ], q.x[ 1 ], 1.5*sqrt( p.m ) );
}
References drawPoint(), SParticule::m, point2DrawingAreaPoint(), SPoint::x, and SParticule::x.
Referenced by on_draw().
drawPoint()
void drawPoint (cairo_t * cr, double x, double y, double r)
Fonction de base qui affiche un disque de centre (x,y) et de rayon r via cairo.
Definition at line 224 of file main.c.
{
  cairo_arc( cr, x, y, r, 0.0, 2.0 * 3.14159626 );
  cairo_fill( cr );
}
Referenced by drawParticule().
fontaine()
void fontaine (Contexte * pCtxt, double p, double x, double y, double vx, double vy, double m)
Fontaine pour créer une particule à la position (x, y), avec la vitesse (vx, vy) et la masse m.
Parameters
p probabilité (entre 0 et 1) qu'une particule soit effectivement créée.
x la coordonnée x de la position où la particule est créée.
y la coordonnée y de la position où la particule est créée.
vx la composante x de la vitesse de la particule.
vy la composante y de la vitesse de la particule.
m la masse de la particule créée.
Definition at line 302 of file main.c.
{
  TabParticules* P = &pCtxt->TabP;
  if ( ( rand() / (double) RAND_MAX ) < p )
    {
      Particule q;
      initParticule( &q, x, y, vx, vy, m );
      TabParticules_ajoute( P, q );
    }
}
References initParticule(), SContexte::TabP, and TabParticules_ajoute().
Referenced by tic().
length2DrawingAreaLength()
double length2DrawingAreaLength (Contexte * pCtxt, double l)
Fait la conversion longueur réelle l vers longueur en pixel dans la zone de dessin.
Parameters
pCtxt le contexte de l'IHM
l la longueur réelle
Returns
la longueur correspondante en pixels.
Definition at line 200 of file main.c.
{
  return pCtxt->width * l / 2.0;
}
References SContexte::width.
main()
int main (int argc, char * argv[])
Definition at line 144 of file main.c.
{
  Contexte context;
  TabParticules_init( &context.TabP );
  /* Passe les arguments à GTK, pour qu'il extrait ceux qui le concernent. */
  gtk_init( &argc, &argv );
  /* Crée une fenêtre. */
  creerIHM( &context );
  /* Rentre dans la boucle d'événements. */
  gtk_main ();
  return 0;
}
References creerIHM(), main(), SContexte::TabP, and TabParticules_init().
on_draw()
gboolean on_draw (GtkWidget * widget, GdkEventExpose * event, gpointer data)
c'est la réaction principale qui va redessiner tout.
Definition at line 163 of file main.c.
{
  // c'est la réaction principale qui va redessiner tout.
  Contexte* pCtxt = (Contexte*) data;
  TabParticules* ptrP = &(pCtxt->TabP);
  // c'est la structure qui permet d'afficher dans une zone de dessin
  // via Cairo
  GdkWindow* window = gtk_widget_get_window(widget);
  cairo_region_t* cairoRegion = cairo_region_create();
  GdkDrawingContext* drawingContext
    = gdk_window_begin_draw_frame( window, cairoRegion );
  cairo_t* cr = gdk_drawing_context_get_cairo_context( drawingContext );
  cairo_set_source_rgb (cr, 1, 1, 1); // choisit le blanc.
  cairo_paint( cr ); // remplit tout dans la couleur choisie.
  // Affiche tous les points en bleu.
  cairo_set_source_rgb (cr, 0, 0, 1);
  for ( int i = 0; i < TabParticules_nb( ptrP ); ++i )
    {
      drawParticule( pCtxt, cr, TabParticules_get( ptrP, i ) );
    }
  // On a fini, on peut détruire la structure.
  gdk_window_end_draw_frame(window,drawingContext);
  // cleanup
  cairo_region_destroy(cairoRegion);
  return TRUE;
}
References drawParticule(), SContexte::TabP, TabParticules_get(), and TabParticules_nb().
Referenced by creerIHM().
point2DrawingAreaPoint()
Point point2DrawingAreaPoint (Contexte * pCtxt, Point p)
Fait la conversion coordonnées réelles de p vers coordonnées de la zone de dessin.
Parameters
pCtxt le contexte de l'IHM
p le point en entrée
Returns
ses coordonnées dans la zone de dessin.
Definition at line 192 of file main.c.
{
  Point q;
  q.x[ 0 ] = ( p.x[ 0 ] + 1.0 ) / 2.0 * pCtxt->width;
  q.x[ 1 ] = ( 1.0 - p.x[ 1 ] ) / 2.0 * pCtxt->height;
  return q;
}
References SContexte::height, SContexte::width, and SPoint::x.
Referenced by drawParticule().
tic()
gint tic (gpointer data)
Fonction appelée régulièrement (tous les DT secondes) et qui s'occupe de (presque tout):
générer de nouvelles particules: fontaine
calculer les forces sur chaque particule: calculDynamique
déplacer les particules et gérer les collisions: deplaceTout
Parameters
data correspond en fait au pointeur vers le Contexte.
Definition at line 314 of file main.c.
{
  Contexte* pCtxt = (Contexte*) data;
  fontaine( pCtxt, 0.25, -0.5, 0.5, 0.3, 0.3, 2.5 );
  calculDynamique( pCtxt );
  deplaceTout( pCtxt );
  g_timeout_add (1000*DT, tic, (gpointer) pCtxt ); // réenclenche le timer.
  return 0;
}
References calculDynamique(), deplaceTout(), DT, fontaine(), and tic().
Referenced by creerIHM(), and tic().
ticAffichage()
gint ticAffichage (gpointer data)
Fonction appelée régulièrement (tous les DT_AFF secondes) et qui s'occupe de demander le réaffichage dela zone de dessin.
Parameters
data correspond en fait au pointeur vers le Contexte.
Definition at line 324 of file main.c.
{
  Contexte* pCtxt = (Contexte*) data;
  char buffer[ 128 ];
  sprintf( buffer, "%d points", TabParticules_nb( &pCtxt->TabP ) );
  gtk_label_set_text( GTK_LABEL( pCtxt->label_nb ), buffer );
  gtk_widget_queue_draw( pCtxt->drawing_area );
  g_timeout_add (1000*DT_AFF, ticAffichage, (gpointer) pCtxt ); // réenclenche le timer.
  return 0;
}
References SContexte::drawing_area, DT_AFF, SContexte::label_nb, SContexte::TabP, TabParticules_nb(), and ticAffichage().
Referenced by creerIHM(), and ticAffichage().
ticDistance()
gint ticDistance (gpointer data)
Fonction appelée régulièrement (tous les secondes) et qui affiche le nombre d'appels à la fonction distance par seconde.
Parameters
data correspond en fait au pointeur vers le Contexte.
Definition at line 335 of file main.c.
{
  Contexte* pCtxt = (Contexte*) data;
  char buffer[ 128 ];
  sprintf( buffer, "%7d nb appels à distance()", getCompteurDistance() ),
  gtk_label_set_text( GTK_LABEL( pCtxt->label_distance ), buffer );
  resetCompteurDistance();
  g_timeout_add (1000, ticDistance, (gpointer) pCtxt ); // réenclenche le timer.
  return 0;
}
References getCompteurDistance(), SContexte::label_distance, resetCompteurDistance(), and ticDistance().
Referenced by creerIHM(), and ticDistance().