INFO607: TP-Proximity/particules.c File Reference
particules.c File Reference
#include <assert.h>
#include <stdlib.h>
#include <math.h>
#include "particules.h"
Functions
void initParticule (Particule *p, double x, double y, double vx, double vy, double m)
void TabParticules_init (TabParticules *tab)
void TabParticules_ajoute (TabParticules *tab, Particule p)
void TabParticules_set (TabParticules *tab, int i, Particule p)
Particule TabParticules_get (TabParticules *tab, int i)
Particule * TabParticules_ref (TabParticules *tab, int i)
int TabParticules_nb (TabParticules *tab)
void TabParticules_termine (TabParticules *tab)
void TabParticules_agrandir (TabParticules *tab)
void TabParticules_supprime_dernier (TabParticules *tab)
void TabParticules_supprime (TabParticules *tab, int i)
Function Documentation
initParticule()
void initParticule (Particule * p, double x, double y, double vx, double vy, double m)
Initialise le point p avec la position (x,y), la vitesse (vx,vy), une masse m et des forces nulles.x
Definition at line 6 of file particules.c.
{
  p->x[0] = x;
  p->x[1] = y;
  p->v[0] = vx;
  p->v[1] = vy;
  p->f[0] = 0.0;
  p->f[1] = 0.0;
  p->m = m;
}
References SParticule::f, SParticule::m, SParticule::v, and SParticule::x.
Referenced by fontaine().
TabParticules_agrandir()
void TabParticules_agrandir (TabParticules * tab)
Utilisé en interne. Agrandit automatiquement le tableau si nécessaire.
Definition at line 63 of file particules.c.
{
  int new_taille = 2*tab->taille;
  Particule* new_pts = (Particule*) malloc( new_taille * sizeof( Particule ) );
  for ( int i = 0; i < tab->nb; ++i )
    new_pts[ i ] = tab->particules[ i ];
  free( tab->particules );
  tab->particules = new_pts;
  tab->taille = new_taille;
}
References STabParticule::nb, STabParticule::particules, and STabParticule::taille.
Referenced by TabParticules_ajoute().
TabParticules_ajoute()
void TabParticules_ajoute (TabParticules * tab, Particule p)
Ajoute si possible le particule p à la fin du tableau de particules tab.
Parameters
tab un pointeur vers une structure TabParticule valide.
p une particule.
Definition at line 25 of file particules.c.
{
  if ( tab->nb == tab->taille )
    TabParticules_agrandir( tab );
  tab->particules[ tab->nb++ ] = p;
}
References STabParticule::nb, STabParticule::particules, TabParticules_agrandir(), and STabParticule::taille.
Referenced by fontaine().
TabParticules_get()
Particule TabParticules_get (TabParticules * tab, int i)
Parameters
tab un pointeur vers une structure TabParticule valide.
i un index valide (entre 0 et TabParticules_nb(tab))
Returns
le i-ème point du tableau de points tab.
Definition at line 38 of file particules.c.
{
  assert ( i < tab->nb );
  return tab->particules[ i ];
}
References STabParticule::particules.
Referenced by on_draw().
TabParticules_init()
void TabParticules_init (TabParticules * tab)
Initialise le tableau de particules tab. Il contient 0 particules initialement, mais peut accueillir jusqu'à 10 particules sans être agrandi.
Parameters
tab un pointeur vers une structure TabParticule.
Definition at line 18 of file particules.c.
{
  tab->taille = 10;
  tab->nb = 0;
  tab->particules = (Particule*) malloc( tab->taille * sizeof( Particule ) );
}
References STabParticule::nb, STabParticule::particules, and STabParticule::taille.
Referenced by main().
TabParticules_nb()
int TabParticules_nb (TabParticules * tab)
Parameters
tab un pointeur vers une structure TabParticule valide.
Returns
le nombre de points utiles stockés dans le tableau de points tab.
Definition at line 50 of file particules.c.
{
  return tab->nb;
}
References STabParticule::nb.
Referenced by calculDynamique(), deplaceTout(), on_draw(), and ticAffichage().
TabParticules_ref()
Particule * TabParticules_ref (TabParticules * tab, int i)
Parameters
tab un pointeur vers une structure TabParticule valide.
i un index valide (entre 0 et TabParticules_nb(tab))
Returns
un pointeur vers le i-ème point du tableau de points tab.
Definition at line 44 of file particules.c.
{
  assert ( i < tab->nb );
  return tab->particules + i;
}
References STabParticule::particules.
Referenced by calculDynamique(), and deplaceTout().
TabParticules_set()
void TabParticules_set (TabParticules * tab, int i, Particule p)
Modifie le i-ème point du tableau de points tab. Il devient le point p.
Parameters
tab un pointeur vers une structure TabParticule valide.
i un index valide (entre 0 et TabParticules_nb(tab))
p une particule.
Definition at line 32 of file particules.c.
{
  assert ( i < tab->nb );
  tab->particules[ i ] = p;
}
References STabParticule::particules.
TabParticules_supprime()
void TabParticules_supprime (TabParticules * tab, int i)
Supprime un élément en position i du tableau. Met le dernier élément du tableau à la place.
Definition at line 80 of file particules.c.
{
  assert ( i >= 0 );
  assert ( i < tab->nb );
  tab->particules[ i ] = tab->particules[ --tab->nb ];
}
References STabParticule::nb, and STabParticule::particules.
Referenced by deplaceTout().
TabParticules_supprime_dernier()
void TabParticules_supprime_dernier (TabParticules * tab)
Supprime le dernier élément du tableau.
Definition at line 74 of file particules.c.
{
  assert( tab->nb > 0 );
  --tab->nb;
}
References STabParticule::nb.
TabParticules_termine()
void TabParticules_termine (TabParticules * tab)
Indique que le tableau de points tab n'est plus utilisé et libère la mémoire associée. Il passe à une taille 0.
Parameters
tab un pointeur vers une structure TabParticule valide.
Definition at line 55 of file particules.c.
{
  if ( tab->particules != NULL ) free( tab->particules );
  tab->taille = 0;
  tab->nb = 0;
  tab->particules = NULL;
}
References STabParticule::nb, STabParticule::particules, and STabParticule::taille.