INFO607: TP-Convex/points.h File Reference
points.h File Reference
Classes
struct SPoint
struct STabPoint
Typedefs
typedef struct SPoint Point
typedef struct STabPoint TabPoints
Functions
void TabPoints_init (TabPoints *tab)
void TabPoints_ajoute (TabPoints *tab, Point p)
void TabPoints_set (TabPoints *tab, int i, Point p)
Point TabPoints_get (TabPoints *tab, int i)
int TabPoints_nb (TabPoints *tab)
void TabPoints_termine (TabPoints *tab)
Typedef Documentation
Point
typedef struct SPoint Point
TabPoints
typedef struct STabPoint TabPoints
Function Documentation
TabPoints_ajoute()
void TabPoints_ajoute (TabPoints * tab, Point p)
Ajoute si possible le point p à la fin du tableau de points tab.
Parameters
tab un pointeur vers une structure TabPoint valide.
p un point.
Definition at line 12 of file points.c.
{
  if ( tab->nb < tab->taille )
    tab->points[ tab->nb++ ] = p;
}
References STabPoint::nb, STabPoint::points, and STabPoint::taille.
Referenced by diskRandom().
TabPoints_get()
Point TabPoints_get (TabPoints * tab, int i)
Parameters
tab un pointeur vers une structure TabPoint valide.
i un index valide (entre 0 et TabPoints_nb(tab))
Returns
le i-ème point du tableau de points tab.
Definition at line 24 of file points.c.
{
  assert ( i < tab->nb );
  return tab->points[ i ];
}
References STabPoint::points.
Referenced by on_draw().
TabPoints_init()
void TabPoints_init (TabPoints * tab)
Initialise le tableau de points tab. Il contient 0 points initialement, mais peut accueillir jusqu'à 100 points sans être agrandi.
Parameters
tab un pointeur vers une structure TabPoint.
Definition at line 5 of file points.c.
{
  tab->taille = 100;
  tab->nb = 0;
  tab->points = (Point*) malloc( tab->taille * sizeof( Point ) );
}
References STabPoint::nb, STabPoint::points, and STabPoint::taille.
Referenced by main().
TabPoints_nb()
int TabPoints_nb (TabPoints * tab)
Parameters
tab un pointeur vers une structure TabPoint valide.
Returns
le nombre de points utiles stockés dans le tableau de points tab.
Definition at line 30 of file points.c.
{
  return tab->nb;
}
References STabPoint::nb.
Referenced by on_draw().
TabPoints_set()
void TabPoints_set (TabPoints * tab, int i, Point p)
Modifie le i-ème point du tableau de points tab. Il devient le point p.
Parameters
tab un pointeur vers une structure TabPoint valide.
i un index valide (entre 0 et TabPoints_nb(tab))
p un point.
Definition at line 18 of file points.c.
{
  assert ( i < tab->nb );
  tab->points[ i ] = p;
}
References STabPoint::points.
TabPoints_termine()
void TabPoints_termine (TabPoints * tab)
Indique que le tableau de points tab n'est plus utilisé et libère la mémoire associée. Il passe à une taille 0.
Parameters
tab un pointeur vers une structure TabPoint valide.
Definition at line 35 of file points.c.
{
  if ( tab->points != NULL ) free( tab->points );
  tab->taille = 0;
  tab->nb = 0;
  tab->points = NULL;
}
References STabPoint::nb, STabPoint::points, and STabPoint::taille.